name: ajTest2
favicon: null
layout_spectrum: 0.9645101132337004
typography_spectrum: 0.631757372058928
title: Test2
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.13407432893291116
  lightness: 0.9225174456369132
  saturation: 0.1698597411159426
  rhythmicContrast: 0.845520936883986
purpose: []
